



 function bitvector_indices_matrix(vecs::Vector{BitVector})
     # Get the column indices where the bit is 1
     idxs = [findall(x -> x == 1, row) for row in vecs]
     # Determine the maximum number of 1s across all rows
     maxlen = maximum(length.(idxs))
     # Pad each row appropriately
     padded = [isempty(r) ? fill(0, maxlen) :
               length(r) == maxlen ? r :
               vcat(r, fill(r[end], maxlen - length(r))) for r in idxs]
     return reduce(vcat, padded')  # Stack transposed row vectors into matrix
 end


function read_data_csv(data_fn; adj_matrix=NaN, max_real_biome=NaN)


    data = readdlm(data_fn, ',', String)
    biomes = unique(data[1,2:end])
    species = data[2:end,1]
    biome_affs_data = data[2:end,2:end]

    if isnan(max_real_biome)
        max_real_biome = length(biomes)
    end

    nbiomes = length(biomes)

    obs_biome_affs = fill(0, length(species), length(biomes)    )
    obs_biome_affs[biome_affs_data.=="1"]  .= 1
    obs_biome_affs[biome_affs_data.=="2"]  .= 2
    obs_biome_affs[biome_affs_data.=="NA"] .= 0
    obs_biome_affs[biome_affs_data.=="NaN"] .= 0

    rf_states = make_rf_states(nbiomes::Int64, max_real_biome)

    obs_tip_states = Vector{Int64}(undef, size(obs_biome_affs, 1))
    missing_state_rows = Int64[]

    for i in axes(obs_biome_affs, 1)
        obs_state = vec(obs_biome_affs[i, :])
        state_ind = findfirst(==(obs_state), rf_states)

        if isnothing(state_ind)
            push!(missing_state_rows, i)
        else
            obs_tip_states[i] = state_ind
        end
    end

    if !isempty(missing_state_rows)
        missing_species = species[missing_state_rows]
        missing_states = [vec(obs_biome_affs[i, :]) for i in missing_state_rows]
        error(
            "Some observed tip states are not present in the RF state space. " *
            "Increase max_real_biome/max_range or fix the affinity table. " *
            "max_real_biome=$(max_real_biome); missing species/states=$(collect(zip(missing_species, missing_states)))"
        )
    end



    forbidden_aff_one_hot = [biome_affs_data[i,:] .== "0" for i in eachindex(species)]
    forbidden_fund = if any(any(row) for row in forbidden_aff_one_hot)
        bitvector_indices_matrix(forbidden_aff_one_hot)
    else
        NaN
    end

    tip_probs = get_emp_tip_probs(rf_states, obs_tip_states, adj_matrix, forbidden_fund)

    return tip_probs, nbiomes, rf_states
end




function RFBS(;data_fn               
             ,tree                 
             ,max_range            
             ,adj_matrix           
             ,iters                 =1000000
             ,iter_trims        =iters/10000
             ,anc_state_sampling=iters/10000
             ,write_interval           =100
             ,proposal_probs           = (rate_move = 10 , clado_move = 5 , rate_zero_switch = 2.0, clado_zero_switch = 0.0)
             ,rate_tuning_par          =1.5
             ,clado_tuning_par         =0.4
             
             ,exponential_prior_rate   =0.5
             
             ,allow_double_gains      = true
             ,allow_double_losses     = false
             ,allow_single_gains      = true
             ,allow_single_losses     = true
             ,allow_real_switches     = true
             ,allow_realfun_switches  = false
             ,ecological              =true
             ,allopatric              =true
             
             
             ,by_biome                = false
             ,by_rf                   = true
             ,by_gainloss             = true
             ,by_doublesingle         = true
             ,output_dirname          = "RFBS_out"
             )



    

    tip_probs_new, nbiomes, rf_states = read_data_csv(data_fn; adj_matrix=adj_matrix, max_real_biome=max_range)



    Prior=exponential_prior_rate
    rate_prior_vec  = [Exponential(Prior)]
    #clado_types     = ["sub_split"]


    # take details to generater Q vectors to map rates to right Q matrix, the Q matrix generated by this function is ignored (just using the simulation function, messy)
    par_matrix, rf_states, move_types, index_vec, move_matrix = make_rf_par_matrix(nbiomes,max_range,
                                                                                    allow_real_switches     , 
                                                                                    allow_realfun_switches,
                                                                                    allow_double_gains , 
                                                                                    allow_double_losses,
                                                                                    allow_single_gains ,
                                                                                    allow_single_losses,
                                                                                    by_biome           ,
                                                                                    by_rf              ,
                                                                                    by_gainloss        ,
                                                                                    by_doublesingle    ,
                                                                                    false )#,absorb_states)

                                                                                    # convert to matrix (rows = vectors)
    rf_states_mat = reduce(vcat, permutedims.(rf_states))

    # write to txt

    cladoPmat_unpar= makeclado_Pmat_equal_prob(rf_states,
    ecological,
    allopatric)



    cladoPmat_sim, clado_probs_start, split_index_vec, sub_index_vec, String_Clado_Mats, clado_prior_dists =make_clado_Pmat(rf_states, ecological, allopatric )


    rate_prior_dists=make_Prior(rate_prior_vec, move_types)



    ntips=length(tree.tlab)
    ed=tree.ed
    edges = cat(ed, [2*ntips ntips + 1], dims = 1)
    triads=maketriads(edges)
    node_path  = get_trav_path_4prun(triads )
    br = branching_times(tree)
    brs = sortslices(br, dims = 1, by = x -> x[5], rev = true)
    


    start_rates           =[rand(rate_prior_dists[i])  for i in eachindex(move_types)]
    start_clado_split_prob=[rand(clado_prior_dists[1]) ]

    #join(round.(start_rates, sigdigits=3),"_" )

    if isdir(output_dirname)==false
        mkdir(output_dirname)
    end

    open(output_dirname*"/state_space" , "w") do io
        writedlm(io,  rf_states_mat)
    end

    log_filename=output_dirname * "/RFBS_log"


    prior_only =false

    realfun_mcmc(start_rates,                                              
                clado_probs_start,
                 iters, 
                 iter_trims,
                  write_interval,
                 anc_state_sampling, 
                 par_matrix, 
                 index_vec,
                  move_types,
                  rate_prior_dists,
                 cladoPmat_unpar,
                 clado_prior_dists, 
                 rf_states, 
                 tip_probs_new, 
                 tree, 
                 log_filename,
                 rate_tuning_par, 
                 clado_tuning_par,
                 proposal_probs, 
                 prior_only,
                 false )
end
